### ISSUE TITLE
中文翻譯? Chinese Translate?

### ISSUE THREAD

**Issue by neslxzhen** [ttdyce/NHentaiViewer#4]
看code似乎是中國人寫的，因為使用支付寶來尋求贊助。

難道沒有簡體中文版本嗎?或是我誤會了?

看code似乎是中国人写的，因为使用支付宝来寻求赞助。

难道没有简体中文版本吗?或是我误会了?

Look at the code seems to be written by the Chinese, because using Alipay to seek Donate.

Is there no Simplified Chinese version? Or am I misunderstanding?

**Comment by ttdyce** [comment]
可以在下個版本加入翻譯功能！ 但我也不知道要過多久才更新，看進度吧。
另外，alipay贊助那邊是個bug，我好像曾經把NHBook 的strings.xml 複製了過來… 我也忘了，反正那個不是我的…

**Comment by neslxzhen** [comment]
我已經幫你修好了，如果可以就拉進去吧

我最近也在寫NH的App，你打了地基真是太好了

**Comment by ttdyce** [comment]
好, 我明天再看看
