### ISSUE TITLE
[NHentaiViewer][v1.0.3]Failed to install the app.

### ISSUE THREAD

**Issue by 44asad** [ttdyce/NHentaiViewer#5]
### Actual Behaviour

App fail to install in my device.
### Expected Behaviour

I expected that i can install and use the app successfully.
### Step to reproduce
* Download the app from release page
* click the app to install
* see the error
### Information
1. App version:v1.0.3
2. Os:Android 8.1.0
3. Device: symphony i72
### Recording of the bug

https://youtu.be/oU5egQ9IY6Y

**Comment by ttdyce** [comment]
Try the signed version, that one should work for your device
https://github.com/ttdyce/NHentaiViewer/releases/download/1.0.3/nhviewer-1.0.3-signed.apk

**Comment by 44asad** [comment]
Ok
