### ISSUE TITLE
About LOGO

### ISSUE THREAD

**Issue by History-exe** [ttdyce/NHentaiViewer#9]
This app has no logo, how about adding one?

**Comment by ttdyce** [comment]
Yeah, I have planned to add a icon with lower priority, maybe 2/3 patches later.

**Comment by History-exe** [comment]
@ttdyce 看评论才知道是国人作者:joy:。另外我发现app的设置界面点不出来。

**Comment by ttdyce** [comment]
現在的版本還沒完成... 下個版本再看看吧 🤔
